// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SmartFlow.Shared.Data;
using SmartFlow.Shared.Enums;
using SmartFlow.Shared.Models;
using SmartFlow.Shared.Models.Ede.Enums;
using System;

namespace SmartFlow.Shared.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SmartFlow.Shared.Data.DataModels.Declaration_Dbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedDate");

                    b.Property<string>("DeNo");

                    b.Property<int>("DeclarationType");

                    b.Property<string>("LastUpdatedDate");

                    b.Property<int>("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("SmartFlow.Shared.Data.DataModels.Profile_Dbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedDate");

                    b.Property<byte[]>("Image");

                    b.Property<string>("LastUpdatedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SmartFlow.Shared.Data.DataModels.Question_Dbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnswerCode");

                    b.Property<string>("AnswerText");

                    b.Property<string>("CreatedDate");

                    b.Property<int?>("Declaration_DboId");

                    b.Property<string>("LastUpdatedDate");

                    b.Property<int?>("Profile_DboId");

                    b.Property<int>("QuestionIdentifier");

                    b.Property<string>("QuestionKey");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("Declaration_DboId");

                    b.HasIndex("Profile_DboId");

                    b.ToTable("Question_Dbo");
                });

            modelBuilder.Entity("SmartFlow.Shared.Data.DataModels.Declaration_Dbo", b =>
                {
                    b.HasOne("SmartFlow.Shared.Data.DataModels.Profile_Dbo", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartFlow.Shared.Data.DataModels.Question_Dbo", b =>
                {
                    b.HasOne("SmartFlow.Shared.Data.DataModels.Declaration_Dbo")
                        .WithMany("Questions")
                        .HasForeignKey("Declaration_DboId");

                    b.HasOne("SmartFlow.Shared.Data.DataModels.Profile_Dbo")
                        .WithMany("Questions")
                        .HasForeignKey("Profile_DboId");
                });
#pragma warning restore 612, 618
        }
    }
}
